# Site settings
title: Frederick Robinson
email: frederick.robinson@gmail.com
description: "Home page of Frederick Robinson."
baseurl: ""
url: "http://www.frrad.com"

# Build settings
markdown: kramdown
permalink: pretty
